manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: davidphilipbarr
      url-base: https://github.com/davidphilipbarr
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: jonnyirwin
      url-base: https://github.com/jonnyirwin
    - name: kilipan
      url-base: https://github.com/kilipan
    - name: jcmkk3
      url-base: https://github.com/jcmkk3
    - name: carrefinho
      url-base: https://github.com/carrefinho
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3-branch
      import: app/west.yml
    - name: nicehatharry
      remote: davidphilipbarr
      clone-depth: 1
      revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-keyboards-phantom
      remote: jonnyirwin
      revision: main
    - name: zmk-keyboards-teenspirit
      remote: kilipan
      revision: main
    - name: zmk-keyboard-berylline
      remote: jcmkk3
      revision: main
    - name: prospector-zmk-module
      remote: carrefinho
      revision: main
  self:
    path: config
